import streamlit as st
import pandas as pd
from database import viewQueryResult
from database import execQuery

def predef_queries():
    q = [   "Number of reservations for each hotel", 
            "Total revenue generated by each room type", 
            "Number of employees in each job title",
            "Number of services offered by each hotel",
            "Employees and Their Jobs",
            "Customer and Reservation Information",
            "Hotel ID and Name with the maximum rating",
            "Hotel ID and Name with the minimum rating",
            "Total number of rooms and employees in each hotel",
            "Names and contact information of customers who have made reservations in hotels with a rating greater than 4",
            "Function 1: Calculate Total Revenue of hotel with HotelID 1",
            "Function 2: Get Available Services For Hotel with HotelID 1",
            "Procedure 1: Calculate the number of reservation days"]
    choice = st.selectbox("Choose a Query: ", q)
    print(choice)
    result = viewQueryResult(q.index(choice)+1)
    #print(result)
    if(choice==q[0]):
        df = pd.DataFrame(result, columns=("HotelName", "ReservationCount"))
        st.dataframe(df)
    elif(choice==q[1]):
        df = pd.DataFrame(result, columns=("room_name", "TotalRevenue"))
        st.dataframe(df)
    elif(choice==q[2]):
        df = pd.DataFrame(result, columns=("job_title", "EmployeeCount"))
        st.dataframe(df)
    elif(choice==q[3]):
        df = pd.DataFrame(result, columns=("HotelName", "TotalServices"))
        st.dataframe(df)
    elif(choice==q[4]):
        df = pd.DataFrame(result, columns=("emp_id", "emp_fname", "emp_lname", "emp_address", "job_id", "job_title"))
        st.dataframe(df)
    elif(choice==q[5]):
        df = pd.DataFrame(result, columns=("cust_id", "cust_fname", "cust_lname", "cust_mail", "res_id", "in_date", "out_date"))
        st.dataframe(df)
    elif(choice==q[6]):
        df = pd.DataFrame(result, columns=("HotelID", "HotelName", "HotelRating"))
        st.dataframe(df)
    elif(choice==q[7]):
        df = pd.DataFrame(result, columns=("HotelID", "HotelName", "HotelRating"))
        st.dataframe(df)
    elif(choice==q[8]):
        df = pd.DataFrame(result, columns=("HotelID", "TotalRooms"))
        st.dataframe(df)
    elif(choice==q[9]):
        df = pd.DataFrame(result, columns=("cust_fname", "cust_lname", "cust_mail", "cust_ph_no"))
        st.dataframe(df)
    elif(choice==q[10]):
        df = pd.DataFrame(result)
        st.dataframe(df)
    elif(choice==q[11]):
        df = pd.DataFrame(result)
        st.dataframe(df)
    elif(choice==q[12]):
        df = pd.DataFrame(result)
        st.dataframe(df)

def query_cmd():
    command = st.text_input("Enter Query")
    if command:
        result = execQuery(command)
        #print(result)
        df = pd.DataFrame(result) 
        st.dataframe(df)

    